### ISSUE TITLE
LINE SDK 4.0.1 and LINE SDK 3.2.2 have different results for userid

### ISSUE THREAD

**Issue by eikaiwason** [line/line-sdk-starter-ios-v2#1]
In LINE SDK 4.0.1, I use

`        NSString * userID = profileInformation.userID;
`

IN LINE SDK 3.2.2, I use

`        NSString *mid = aResult[@"mid"];
`

I expected `userID` to be the same as `mid` but they are different.  How can I tell if it is the same user for LINE login when I upgrade to LINE SDK 4.0.1?  I have many users registered using LINE SDK 3.2.2

**Comment by mrmaakun** [comment]
@eikaiwason 

We recently added an entry to our FAQ related to this issue. Please take a look and let us know if you have any questions:

https://developers.line.me/faq#anc6-3

**Comment by GuitarSucks** [comment]
Closing this issue
