### ISSUE TITLE
LINE Login Failed with Error: Error Domain=LineSDKInternalErrorDomain Code=1 "The operation couldn’t be completed. (NLChannelGatewayErrorDomain error 102.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (NLChannelGatewayErrorDomain error 102.)}

### ISSUE THREAD

**Issue by arno608rw** [line/line-sdk-starter-ios-v2#12]
LINE Login Failed with Error: Error Domain=LineSDKInternalErrorDomain Code=1 "The operation couldn’t be completed. (NLChannelGatewayErrorDomain error 102.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (NLChannelGatewayErrorDomain error 102.)}

**Comment by mrmaakun** [comment]
Hi @arno608rw 

This comment in the [line-sdk-starter-ios](https://github.com/line/line-sdk-starter-ios) repository might be helpful.

https://github.com/line/line-sdk-starter-ios/issues/10#issuecomment-258736935

**Comment by arno608rw** [comment]
@mrmaakun  URL Scheme required to be in the format of this?
line3rdp.com.xxx.xxxx or line3rdp.${com.xxx.xxxx}
It not work

**Comment by arno608rw** [comment]
SDK 3.x.x work! but SDK 4.0.2 not work and same error

**Comment by mrmaakun** [comment]
@arno608rw 

it should be in the format  ```line3rdp.${your bundle identifier}```

So if your bundle identifier was "line.line-sdk-starter-objc-v2", your URL Scheme should be "line3rdp.line.line-sdk-starter-objc-v2".

**Comment by mrmaakun** [comment]
@arno608rw 

The causes of this error are the same in 3.x.x and 4.0.2. Please check to see that you are using the bundle ID that you have registered in the Channel Console in your SDK 4.0.2 and that the user being used to log in is properly registered in the channel ROLES.

Have you tried using the Objective C starter application to log into SDK 4.0.2? If you set the Channel ID in Info.plist to your channel ID and register `line.line-sdk-starter-objc-v2` as your iOS Bundle ID and `line3rdp.line.line-sdk-starter-objc-v2` as your iOS Scheme in the Channel Console, it should work as is.

**Comment by arno608rw** [comment]
if i have Bundle ID xxx.yyy.zzz

![screen shot 2560-06-21 at 10 07 07 am](https://user-images.githubusercontent.com/3774145/27365284-7238bf7e-5669-11e7-869a-131096b28f79.png)

**Comment by arno608rw** [comment]
I work on login by web but not work in app line

**Comment by arno608rw** [comment]
OK thank!! @mrmaakun It worked.

**Comment by mrmaakun** [comment]
@arno608rw Glad to hear.
