### ISSUE TITLE
Error Domain=LineSDKInternalErrorDomain Code=3 "Cancel authentication." UserInfo={NSLocalizedDescription=Cancel authentication.}

### ISSUE THREAD

**Issue by qiyer** [line/line-sdk-starter-ios-v2#14]
Error Domain=LineSDKInternalErrorDomain Code=3 "Cancel authentication." UserInfo={NSLocalizedDescription=Cancel authentication.}

How to fix  it ?
Thanks!

**Comment by qiyer** [comment]
Version of LINE iOS SDK that I use is 4.0.2 (My channel id is 1524215952)
Login success by Safari  ,and back to my app throw error:  Error Domain=LineSDKInternalErrorDomain Code=3 "Cancel authentication." UserInfo={NSLocalizedDescription=Cancel authentication.} 

test device: iphone 6 plus

**Comment by mrmaakun** [comment]
Hi @qiyer

Did you add the code to handle the return to your app in your app delegate?

```objc
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary *)options
{
    return [[LineSDKLogin sharedInstance] handleOpenURL:url];
}
```
(https://developers.line.me/ios/development-with-sdk-v2#delegate)

**Comment by qiyer** [comment]
Thanks,  i will try. 
I try again success.

**Comment by qiyer** [comment]
New problem, why iphone or ipad  cann't login with line app in China (even if by vpn) ? We can only login through safari.  Android can login with line app (with vpn).
